/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as PublicVideosRouteImport } from './routes/_public.videos'
import { Route as PublicTrackOrderRouteImport } from './routes/_public.track-order'
import { Route as PublicTermsRouteImport } from './routes/_public.terms'
import { Route as PublicSustainabilityRouteImport } from './routes/_public.sustainability'
import { Route as PublicQuoteRouteImport } from './routes/_public.quote'
import { Route as PublicPrivacyRouteImport } from './routes/_public.privacy'
import { Route as PublicManufacturingRouteImport } from './routes/_public.manufacturing'
import { Route as PublicHeritageRouteImport } from './routes/_public.heritage'
import { Route as PublicGalleryRouteImport } from './routes/_public.gallery'
import { Route as PublicFaqRouteImport } from './routes/_public.faq'
import { Route as PublicFactoryRouteImport } from './routes/_public.factory'
import { Route as PublicDownloadsRouteImport } from './routes/_public.downloads'
import { Route as PublicContactRouteImport } from './routes/_public.contact'
import { Route as PublicCertificationsRouteImport } from './routes/_public.certifications'
import { Route as PublicCategoriesRouteImport } from './routes/_public.categories'
import { Route as PublicCatalogRouteImport } from './routes/_public.catalog'
import { Route as PublicCareersRouteImport } from './routes/_public.careers'
import { Route as PublicAboutRouteImport } from './routes/_public.about'
import { Route as PublicProjectsIndexRouteImport } from './routes/_public.projects.index'
import { Route as PublicProductsIndexRouteImport } from './routes/_public.products.index'
import { Route as PublicBlogIndexRouteImport } from './routes/_public.blog.index'
import { Route as PublicProjectsSlugRouteImport } from './routes/_public.projects.$slug'
import { Route as PublicProductsSlugRouteImport } from './routes/_public.products.$slug'
import { Route as PublicBlogSlugRouteImport } from './routes/_public.blog.$slug'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicVideosRoute = PublicVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => PublicRoute,
} as any)
const PublicTrackOrderRoute = PublicTrackOrderRouteImport.update({
  id: '/track-order',
  path: '/track-order',
  getParentRoute: () => PublicRoute,
} as any)
const PublicTermsRoute = PublicTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSustainabilityRoute = PublicSustainabilityRouteImport.update({
  id: '/sustainability',
  path: '/sustainability',
  getParentRoute: () => PublicRoute,
} as any)
const PublicQuoteRoute = PublicQuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPrivacyRoute = PublicPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => PublicRoute,
} as any)
const PublicManufacturingRoute = PublicManufacturingRouteImport.update({
  id: '/manufacturing',
  path: '/manufacturing',
  getParentRoute: () => PublicRoute,
} as any)
const PublicHeritageRoute = PublicHeritageRouteImport.update({
  id: '/heritage',
  path: '/heritage',
  getParentRoute: () => PublicRoute,
} as any)
const PublicGalleryRoute = PublicGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => PublicRoute,
} as any)
const PublicFaqRoute = PublicFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => PublicRoute,
} as any)
const PublicFactoryRoute = PublicFactoryRouteImport.update({
  id: '/factory',
  path: '/factory',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDownloadsRoute = PublicDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCertificationsRoute = PublicCertificationsRouteImport.update({
  id: '/certifications',
  path: '/certifications',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCategoriesRoute = PublicCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCatalogRoute = PublicCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCareersRoute = PublicCareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const PublicProjectsIndexRoute = PublicProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicProductsIndexRoute = PublicProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicBlogIndexRoute = PublicBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicProjectsSlugRoute = PublicProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const PublicProductsSlugRoute = PublicProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const PublicBlogSlugRoute = PublicBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => PublicRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminRoute
  '/about': typeof PublicAboutRoute
  '/careers': typeof PublicCareersRoute
  '/catalog': typeof PublicCatalogRoute
  '/categories': typeof PublicCategoriesRoute
  '/certifications': typeof PublicCertificationsRoute
  '/contact': typeof PublicContactRoute
  '/downloads': typeof PublicDownloadsRoute
  '/factory': typeof PublicFactoryRoute
  '/faq': typeof PublicFaqRoute
  '/gallery': typeof PublicGalleryRoute
  '/heritage': typeof PublicHeritageRoute
  '/manufacturing': typeof PublicManufacturingRoute
  '/privacy': typeof PublicPrivacyRoute
  '/quote': typeof PublicQuoteRoute
  '/sustainability': typeof PublicSustainabilityRoute
  '/terms': typeof PublicTermsRoute
  '/track-order': typeof PublicTrackOrderRoute
  '/videos': typeof PublicVideosRoute
  '/blog/$slug': typeof PublicBlogSlugRoute
  '/products/$slug': typeof PublicProductsSlugRoute
  '/projects/$slug': typeof PublicProjectsSlugRoute
  '/blog/': typeof PublicBlogIndexRoute
  '/products/': typeof PublicProductsIndexRoute
  '/projects/': typeof PublicProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminRoute
  '/about': typeof PublicAboutRoute
  '/careers': typeof PublicCareersRoute
  '/catalog': typeof PublicCatalogRoute
  '/categories': typeof PublicCategoriesRoute
  '/certifications': typeof PublicCertificationsRoute
  '/contact': typeof PublicContactRoute
  '/downloads': typeof PublicDownloadsRoute
  '/factory': typeof PublicFactoryRoute
  '/faq': typeof PublicFaqRoute
  '/gallery': typeof PublicGalleryRoute
  '/heritage': typeof PublicHeritageRoute
  '/manufacturing': typeof PublicManufacturingRoute
  '/privacy': typeof PublicPrivacyRoute
  '/quote': typeof PublicQuoteRoute
  '/sustainability': typeof PublicSustainabilityRoute
  '/terms': typeof PublicTermsRoute
  '/track-order': typeof PublicTrackOrderRoute
  '/videos': typeof PublicVideosRoute
  '/': typeof PublicIndexRoute
  '/blog/$slug': typeof PublicBlogSlugRoute
  '/products/$slug': typeof PublicProductsSlugRoute
  '/projects/$slug': typeof PublicProjectsSlugRoute
  '/blog': typeof PublicBlogIndexRoute
  '/products': typeof PublicProductsIndexRoute
  '/projects': typeof PublicProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/admin': typeof AdminRoute
  '/_public/about': typeof PublicAboutRoute
  '/_public/careers': typeof PublicCareersRoute
  '/_public/catalog': typeof PublicCatalogRoute
  '/_public/categories': typeof PublicCategoriesRoute
  '/_public/certifications': typeof PublicCertificationsRoute
  '/_public/contact': typeof PublicContactRoute
  '/_public/downloads': typeof PublicDownloadsRoute
  '/_public/factory': typeof PublicFactoryRoute
  '/_public/faq': typeof PublicFaqRoute
  '/_public/gallery': typeof PublicGalleryRoute
  '/_public/heritage': typeof PublicHeritageRoute
  '/_public/manufacturing': typeof PublicManufacturingRoute
  '/_public/privacy': typeof PublicPrivacyRoute
  '/_public/quote': typeof PublicQuoteRoute
  '/_public/sustainability': typeof PublicSustainabilityRoute
  '/_public/terms': typeof PublicTermsRoute
  '/_public/track-order': typeof PublicTrackOrderRoute
  '/_public/videos': typeof PublicVideosRoute
  '/_public/': typeof PublicIndexRoute
  '/_public/blog/$slug': typeof PublicBlogSlugRoute
  '/_public/products/$slug': typeof PublicProductsSlugRoute
  '/_public/projects/$slug': typeof PublicProjectsSlugRoute
  '/_public/blog/': typeof PublicBlogIndexRoute
  '/_public/products/': typeof PublicProductsIndexRoute
  '/_public/projects/': typeof PublicProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/careers'
    | '/catalog'
    | '/categories'
    | '/certifications'
    | '/contact'
    | '/downloads'
    | '/factory'
    | '/faq'
    | '/gallery'
    | '/heritage'
    | '/manufacturing'
    | '/privacy'
    | '/quote'
    | '/sustainability'
    | '/terms'
    | '/track-order'
    | '/videos'
    | '/blog/$slug'
    | '/products/$slug'
    | '/projects/$slug'
    | '/blog/'
    | '/products/'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/about'
    | '/careers'
    | '/catalog'
    | '/categories'
    | '/certifications'
    | '/contact'
    | '/downloads'
    | '/factory'
    | '/faq'
    | '/gallery'
    | '/heritage'
    | '/manufacturing'
    | '/privacy'
    | '/quote'
    | '/sustainability'
    | '/terms'
    | '/track-order'
    | '/videos'
    | '/'
    | '/blog/$slug'
    | '/products/$slug'
    | '/projects/$slug'
    | '/blog'
    | '/products'
    | '/projects'
  id:
    | '__root__'
    | '/_public'
    | '/admin'
    | '/_public/about'
    | '/_public/careers'
    | '/_public/catalog'
    | '/_public/categories'
    | '/_public/certifications'
    | '/_public/contact'
    | '/_public/downloads'
    | '/_public/factory'
    | '/_public/faq'
    | '/_public/gallery'
    | '/_public/heritage'
    | '/_public/manufacturing'
    | '/_public/privacy'
    | '/_public/quote'
    | '/_public/sustainability'
    | '/_public/terms'
    | '/_public/track-order'
    | '/_public/videos'
    | '/_public/'
    | '/_public/blog/$slug'
    | '/_public/products/$slug'
    | '/_public/projects/$slug'
    | '/_public/blog/'
    | '/_public/products/'
    | '/_public/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  AdminRoute: typeof AdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/videos': {
      id: '/_public/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof PublicVideosRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/track-order': {
      id: '/_public/track-order'
      path: '/track-order'
      fullPath: '/track-order'
      preLoaderRoute: typeof PublicTrackOrderRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/terms': {
      id: '/_public/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof PublicTermsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/sustainability': {
      id: '/_public/sustainability'
      path: '/sustainability'
      fullPath: '/sustainability'
      preLoaderRoute: typeof PublicSustainabilityRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/quote': {
      id: '/_public/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof PublicQuoteRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/privacy': {
      id: '/_public/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PublicPrivacyRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/manufacturing': {
      id: '/_public/manufacturing'
      path: '/manufacturing'
      fullPath: '/manufacturing'
      preLoaderRoute: typeof PublicManufacturingRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/heritage': {
      id: '/_public/heritage'
      path: '/heritage'
      fullPath: '/heritage'
      preLoaderRoute: typeof PublicHeritageRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/gallery': {
      id: '/_public/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof PublicGalleryRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/faq': {
      id: '/_public/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof PublicFaqRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/factory': {
      id: '/_public/factory'
      path: '/factory'
      fullPath: '/factory'
      preLoaderRoute: typeof PublicFactoryRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/downloads': {
      id: '/_public/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof PublicDownloadsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/certifications': {
      id: '/_public/certifications'
      path: '/certifications'
      fullPath: '/certifications'
      preLoaderRoute: typeof PublicCertificationsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/categories': {
      id: '/_public/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof PublicCategoriesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/catalog': {
      id: '/_public/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof PublicCatalogRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/careers': {
      id: '/_public/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof PublicCareersRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/projects/': {
      id: '/_public/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof PublicProjectsIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/products/': {
      id: '/_public/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof PublicProductsIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/blog/': {
      id: '/_public/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof PublicBlogIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/projects/$slug': {
      id: '/_public/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof PublicProjectsSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/products/$slug': {
      id: '/_public/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof PublicProductsSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/blog/$slug': {
      id: '/_public/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof PublicBlogSlugRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicCareersRoute: typeof PublicCareersRoute
  PublicCatalogRoute: typeof PublicCatalogRoute
  PublicCategoriesRoute: typeof PublicCategoriesRoute
  PublicCertificationsRoute: typeof PublicCertificationsRoute
  PublicContactRoute: typeof PublicContactRoute
  PublicDownloadsRoute: typeof PublicDownloadsRoute
  PublicFactoryRoute: typeof PublicFactoryRoute
  PublicFaqRoute: typeof PublicFaqRoute
  PublicGalleryRoute: typeof PublicGalleryRoute
  PublicHeritageRoute: typeof PublicHeritageRoute
  PublicManufacturingRoute: typeof PublicManufacturingRoute
  PublicPrivacyRoute: typeof PublicPrivacyRoute
  PublicQuoteRoute: typeof PublicQuoteRoute
  PublicSustainabilityRoute: typeof PublicSustainabilityRoute
  PublicTermsRoute: typeof PublicTermsRoute
  PublicTrackOrderRoute: typeof PublicTrackOrderRoute
  PublicVideosRoute: typeof PublicVideosRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicBlogSlugRoute: typeof PublicBlogSlugRoute
  PublicProductsSlugRoute: typeof PublicProductsSlugRoute
  PublicProjectsSlugRoute: typeof PublicProjectsSlugRoute
  PublicBlogIndexRoute: typeof PublicBlogIndexRoute
  PublicProductsIndexRoute: typeof PublicProductsIndexRoute
  PublicProjectsIndexRoute: typeof PublicProjectsIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicCareersRoute: PublicCareersRoute,
  PublicCatalogRoute: PublicCatalogRoute,
  PublicCategoriesRoute: PublicCategoriesRoute,
  PublicCertificationsRoute: PublicCertificationsRoute,
  PublicContactRoute: PublicContactRoute,
  PublicDownloadsRoute: PublicDownloadsRoute,
  PublicFactoryRoute: PublicFactoryRoute,
  PublicFaqRoute: PublicFaqRoute,
  PublicGalleryRoute: PublicGalleryRoute,
  PublicHeritageRoute: PublicHeritageRoute,
  PublicManufacturingRoute: PublicManufacturingRoute,
  PublicPrivacyRoute: PublicPrivacyRoute,
  PublicQuoteRoute: PublicQuoteRoute,
  PublicSustainabilityRoute: PublicSustainabilityRoute,
  PublicTermsRoute: PublicTermsRoute,
  PublicTrackOrderRoute: PublicTrackOrderRoute,
  PublicVideosRoute: PublicVideosRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicBlogSlugRoute: PublicBlogSlugRoute,
  PublicProductsSlugRoute: PublicProductsSlugRoute,
  PublicProjectsSlugRoute: PublicProjectsSlugRoute,
  PublicBlogIndexRoute: PublicBlogIndexRoute,
  PublicProductsIndexRoute: PublicProductsIndexRoute,
  PublicProjectsIndexRoute: PublicProjectsIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  AdminRoute: AdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
